version: "3"
services:
  dps-smoketest:
    build:
      context: .
    network_mode: "host"
    container_name: dps-smoketest
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
  prison-api:
    image: ghcr.io/ministryofjustice/prison-api:latest
    container_name: prison-api
    depends_on:
      - hmpps-auth
    ports:
      - "8093:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
  prisoner-search:
    image: ghcr.io/ministryofjustice/hmpps-prisoner-search:latest
    networks:
      - hmpps
    container_name: prisoner-search
    ports:
      - "8097:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=localstack,dev
  localstack:
    image: localstack/localstack:4
    networks:
      - hmpps
    container_name: localstack-smoke
    ports:
      - "4566:4566"
      - "8999:8080"
    environment:
      - SERVICES=es,sqs
      - ES_PORT_EXTERNAL=4571
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

networks:
  hmpps:
