oauth:
  endpoint:
    url: http://localhost:8090/auth

prisonapi:
  endpoint.url: http://localhost:8093

prisonersearch:
  endpoint.url: http://localhost:8091

test:
  maxLengthSeconds: 10
  resultPollMs: 1000

smoketest:
  client:
    client-id: smoke-test-client
    client-secret: clientsecret

server:
  shutdown: immediate
