spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

oauth:
  endpoint:
    url: http://localhost:8080

prisonapi:
  endpoint.url: http://localhost:8093

community:
  endpoint.url: http://localhost:8096

probationoffendersearch:
  endpoint.url: http://localhost:8097

test:
  maxLengthSeconds: 10
  resultPollMs: 1000

smoketest:
  client:
    client-id: smoke-test-client
    client-secret: password123456

server:
  shutdown: immediate
