# Values here are the same across all environments

generic-service:
  nameOverride: dps-smoketest

  serviceAccountName: dps-smoketest

  image:
    repository: quay.io/hmpps/dps-smoketest
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    tlsSecretName: dps-smoketest-cert

  # Environment variables to load into the deployment
  env:
    SERVER_PORT: 8080
    JAVA_OPTS: "-Xmx512m"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    SPRING_PROFILES_ACTIVE: "logstash"
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    dps-smoketest:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "OAUTH_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "OAUTH_CLIENT_SECRET"
    domain-events-dps-smoketest-queue:
      HMPPS_SQS_QUEUES_HMPPSEVENTQUEUE_QUEUE_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: dps-smoketest
  alertSeverity: syscon
