generic-service:
  nameOverride: dps-smoketest
  productId: DPS060
  
  serviceAccountName: dps-smoketest

  image:
    repository: ghcr.io/ministryofjustice/dps-smoketest
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    tlsSecretName: dps-smoketest-cert

  env:
    SERVER_PORT: 8080
    JAVA_OPTS: "-Xmx512m"
    SPRING_PROFILES_ACTIVE: "logstash"

  namespace_secrets:
    dps-smoketest-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    dps-smoketest-client-creds:
      OAUTH_CLIENT_ID: "API_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "API_CLIENT_SECRET"
    domain-events-dps-smoketest-queue:
      HMPPS_SQS_QUEUES_HMPPSEVENTQUEUE_QUEUE_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal
      - circleci

generic-prometheus-alerts:
  targetApplication: dps-smoketest
  alertSeverity: syscon
  sqsAlertsTotalMessagesThreshold: 50
