# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/dps-smoketest
  tag: latest
  port: 8080

ingress:
  enabled: true
  enable_whitelist: false
  hosts:
    - host: dps-smoketest-dev.hmpps.service.justice.gov.uk
      cert_secret: dps-smoketest-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  OAUTH_ENDPOINT_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
