---
# Environment specific values, override helm_deploy/dps-smoketest/values.yaml

generic-service:
  replicaCount: 2
  ingress:
    host: dps-smoketest-dev.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '7 6 * * 1-5' # Start at 6.07am UTC Monday-Friday
    shutdown: '59 21 * * 1-5' # Stop at 9.59pm UTC Monday-Friday

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    PRISONAPI_ENDPOINT_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    PRISONERSEARCH_ENDPOINT_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

  allowlist: null

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
  sqsAlertsQueueNames:
    - "Digital-Prison-Services-prod-dps_smoketest_dev_hmpps_queue"
